#自定义配置
zigar:
  hostname: 127.0.0.1
  eureka:
    username: zigar
    password: 123456

spring:
  application:
    name: server-zuul #指定服务名
  zipkin:
    base-url: http://${zigar.hostname}:9411/
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  rabbitmq: #RabbitMQ相关的配置
    host: ${zigar.hostname}
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/users/current
      prefer-token-info: false
    client:
      id: client_3
      client-secret: 123456
      access-token-uri: http://localhost:8002/oauth/token
      user-authorization-uri: http://localhost:8002/oauth/authorize
      grant-type: client_credentials
      scope: select

#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

###服务网关
zuul:
  routes: #定义服务转发规则
    file-service: #file-service这个名字任意取的
      serviceId: service-file
      path: /service-file/** #配置请求URL的请求规则
    user-service: #user-service这个名字任意取的
      serviceId: service-user
      path: /service-user/** #配置请求URL的请求规则
  #以下两个配置不配置会导致zuul请求其他服务无权限
  add-proxy-headers: true
  sensitiveHeaders:

logging:
  level:
    root: info