spring:
  application:
    name: @mvn.server.config.app.name@ #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: @mvn.config.server.git.uri@
          username: @mvn.config.server.git.username@
          password: @mvn.config.server.git.password@
      label: master    #分支名称
  rabbitmq: #RabbitMQ相关的配置 注意：rabbitmq从3.3.0开始禁止使用guest/guest权限通过除localhost外的访问
    host: @mvn.rabbitmq.hostname@
    port: @mvn.rabbitmq.port@
    username: @mvn.rabbitmq.username@
    password: @mvn.rabbitmq.password@
#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: @mvn.eureka.client.serviceUrl.defaultZone@