#自定义配置
zigar:
  hostname: 127.0.0.1
  eureka:
    username: zigar
    password: 123456

#系统配置
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://${zigar.hostname}:3306/zigar_cloud_user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zigar_user_admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
  zipkin:
    base-url: http://${zigar.hostname}:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  rabbitmq: #RabbitMQ相关的配置
    host: ${zigar.hostname}
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/users/current
      prefer-token-info: false
    client:
      id: client_3
      client-secret: 123456
      access-token-uri: http://localhost:8002/oauth/token
      user-authorization-uri: http://localhost:8002/oauth/authorize
      grant-type: client_credenti als
      scope: select

#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:8761/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:8762/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:8763/eureka/

# 在feign中开启熔断器
feign:
  hystrix:
    enabled: true

#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info