#自定义配置
zigar:
  hostname: localhost
  eureka:
    username: zigar
    password: 123456

#系统配置

spring:
  application:
    name: server-rabbitmq
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
  zipkin:
    base-url: http://${zigar.hostname}:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  rabbitmq: #RabbitMQ相关的配置
    host: ${zigar.hostname}
    port: 5672
    username: guest
    password: guest

#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:7100/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:8100/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:9100/eureka/

logging:
  level:
    root: info